"""Add LinkedInPost Table

Revision ID: 2b1644f4a746
Revises: b3c272b6f56f
Create Date: 2025-08-22 12:12:35.744548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1644f4a746'
down_revision = 'b3c272b6f56f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_posts_id'), 'linkedin_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_posts_id'), table_name='linkedin_posts')
    op.drop_table('linkedin_posts')
    # ### end Alembic commands ### 