"""Update LinkedInPost Table

Revision ID: 7c665f4419ff
Revises: 2b1644f4a746
Create Date: 2025-08-22 12:41:39.847064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c665f4419ff'
down_revision = '2b1644f4a746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_posts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('linkedin_posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('linkedin_posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_posts', 'updated_at')
    op.drop_column('linkedin_posts', 'created_at')
    op.drop_column('linkedin_posts', 'is_deleted')
    # ### end Alembic commands ### 